/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.spark.eventhubs.client

import java.time.Duration
import java.util.concurrent._

import com.azure.messaging.eventhubs._
import org.apache.spark.SparkEnv
import org.apache.spark.eventhubs.utils.MetricPlugin
import org.apache.spark.eventhubs.utils.RetryUtils.{ after, retryJava, retryNotNull }
import org.apache.spark.eventhubs.{
  DefaultConsumerGroup,
  EventHubsConf,
  EventHubsUtils,
  NameAndPartition,
  SequenceNumber,
  PartitionPerformanceReceiver
}
import org.apache.spark.internal.Logging
import org.apache.spark.util.RpcUtils

import scala.collection.JavaConverters._
import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.duration._
import scala.concurrent.{ Await, Awaitable, Future, Promise }

private[client] class CachedReceivedData (startSeqNo: SequenceNumber,
                                          batchSize: Int,
                                          cachedData: Seq[EventData]) {

    def matchSeqNoAndBatchSize(reqStartSeqNo: SequenceNumber, reqBatchSize: Int): Boolean = {
      if ((startSeqNo == reqStartSeqNo) && (batchSize == reqBatchSize)) {
        return true
      }
        false
    }

    def getCachedDataIterator(): Iterator[EventData] = {
      cachedData.iterator
    }
}

private[spark] trait CachedReceiver {
  private[eventhubs] def receive(ehConf: EventHubsConf,
                                 nAndP: NameAndPartition,
                                 requestSeqNo: SequenceNumber,
                                 batchSize: Int): Iterator[EventData]
}

/**
 * An Event Hubs receiver instance that is cached on a Spark Executor to be
 * reused across batches. In Structured Streaming and Spark Streaming,
 * partitions are generated on the same executors across batches, so that
 * receivers can be cached are reused for maximum efficiency. Receiver caching
 * allows the underlying consumer clients to prefetch [[EventData]] from
 * the service before DataFrames or RDDs are generated by Spark.
 *
 * Track 2: Uses EventHubsConsumerClient for consuming events from partitions.
 * This class creates and maintains a connection with the Event Hubs service.
 *
 * @param ehConf the [[EventHubsConf]] which contains the connection string used to connect to Event Hubs
 * @param nAndP  the Event Hub name and partition that the receiver is connected to.
 */
private[client] class CachedEventHubsReceiver private (ehConf: EventHubsConf,
                                                       nAndP: NameAndPartition,
                                                       startSeqNo: SequenceNumber)
    extends Logging {

  type AwaitTimeoutException = java.util.concurrent.TimeoutException

  import org.apache.spark.eventhubs._

  private lazy val namespaceUri: String = ehConf.namespaceUri
  private lazy val consumerGroup = ehConf.consumerGroup.getOrElse(DefaultConsumerGroup)

  private lazy val metricPlugin: Option[MetricPlugin] = ehConf.metricPlugin()

  // Track 2: Use EventHubsConsumerClient from the pool
  private lazy val consumerClient: EventHubsConsumerClient = ClientConnectionPool.getConsumerClient(ehConf)

  // Track 2: Receive state for the partition
  private var lastReceivedSeqNo: SequenceNumber = -1
  private var currentEventPosition: EventPosition = EventPosition.fromSequenceNumber(startSeqNo)
  private var isOpen: Boolean = true

  private var cachedData: CachedReceivedData = new CachedReceivedData(-1, -1, null)

  private def createReceiver(seqNo: SequenceNumber): EventPosition = {
    val taskId = EventHubsUtils.getTaskId
    logInfo(
      s"(TID $taskId) creating receiver for namespaceUri: $namespaceUri EventHubNameAndPartition: $nAndP " +
        s"consumer group: $consumerGroup. seqNo: $seqNo")
    // Track 2: Set the starting position for the receiver
    EventPosition.fromSequenceNumber(seqNo)
  }

  private def lastReceivedOffset(): Future[Long] = {
    Future.successful(lastReceivedSeqNo)
  }

  private def receiveOne(timeout: Duration, msg: String): Future[Iterable[EventData]] = {
    def receiveOneWithRetry(timeout: Duration,
                            msg: String,
                            retryCount: Int): Future[Iterable[EventData]] = {
      if (!isOpen && retryCount < RetryCount) {
        val taskId = EventHubsUtils.getTaskId
        logInfo(
          s"(TID $taskId) receiver is not opened yet. Will retry {$retryCount} for namespaceUri: $namespaceUri " +
            s"EventHubNameAndPartition: $nAndP consumer group: $consumerGroup")

        val retry = retryCount + 1
        after(WaitInterval.milliseconds)(receiveOneWithRetry(timeout, msg, retry))
      } else {
        // Track 2: Receive events from partition using consumer client
        val future = Future {
          try {
            val events = consumerClient.receiveFromPartition(nAndP.partitionId.toString, currentEventPosition)
              .blockFirst(timeout)
            if (events != null && events.size() > 0) {
              logDebug(s"(TID ${EventHubsUtils.getTaskId}) Received ${events.size()} events from partition ${nAndP.partitionId}")
              // Update the position for next receive
              val lastEvent = events.last
              lastReceivedSeqNo = lastEvent.getSequenceNumber
              currentEventPosition = EventPosition.fromSequenceNumber(lastReceivedSeqNo + 1)
              events
            } else {
              logDebug(s"(TID ${EventHubsUtils.getTaskId}) No events received from partition ${nAndP.partitionId}")
              java.util.Collections.emptyList[EventData]()
            }
          } catch {
            case e: Exception =>
              logError(s"Error receiving from partition ${nAndP.partitionId}", e)
              throw e
          }
        }
        future
      }
    }
    receiveOneWithRetry(timeout, msg, 0)
  }

  private def closeReceiver(): Future[Void] = {
    // Track 2: Consumer client lifecycle is managed by the pool
    val dummyResult = Promise[Void]()
    dummyResult success null
    Future.successful(null)
  }

  private def recreateReceiver(seqNo: SequenceNumber): Unit = {
    val taskId = EventHubsUtils.getTaskId
    val startTimeNs = System.nanoTime()
    def elapsedTimeNs = System.nanoTime() - startTimeNs

    // Track 2: Reset the receiver position
    Await.result(closeReceiver(), ehConf.internalOperationTimeout)
    currentEventPosition = createReceiver(seqNo)
    lastReceivedSeqNo = seqNo - 1
    isOpen = true

    val elapsedTimeMs = TimeUnit.NANOSECONDS.toMillis(elapsedTimeNs)
    logInfo(s"(TID $taskId) Finished recreating a receiver for namespaceUri: $namespaceUri EventHubNameAndPartition: " +
      s"$nAndP consumer group: $consumerGroup: $elapsedTimeMs ms")
  }

  private def checkCursor(requestSeqNo: SequenceNumber): Future[Iterable[EventData]] = {
    val taskId = EventHubsUtils.getTaskId

    val lastReceivedSeqNoResult =
      Await.result(lastReceivedOffset(), ehConf.internalOperationTimeout)

    // Track 2: Check if we need to recreate the receiver
    if ((lastReceivedSeqNoResult > -1 && lastReceivedSeqNoResult + 1 != requestSeqNo) ||
        !isOpen) {
      logInfo(s"(TID $taskId) checkCursor. Recreating a receiver for namespaceUri: $namespaceUri " +
        s"EventHubNameAndPartition: $nAndP consumer group: $consumerGroup. requestSeqNo: $requestSeqNo, " +
        s"lastReceivedSeqNo: $lastReceivedSeqNoResult, isOpen: ${isOpen}")

      recreateReceiver(requestSeqNo)
    }

    val event = awaitReceiveMessage(
      receiveOne(ehConf.receiverTimeout.getOrElse(DefaultReceiverTimeout), "checkCursor initial"),
      requestSeqNo)
    val receivedSeqNo = event.iterator.next.getSequenceNumber

    if (receivedSeqNo != requestSeqNo) {
      logInfo(
        s"(TID $taskId) checkCursor. Recreating a receiver for namespaceUri: $namespaceUri EventHubNameAndPartition:" +
          s" $nAndP consumer group: $consumerGroup. requestSeqNo: $requestSeqNo, receivedSeqNo: $receivedSeqNo")
      recreateReceiver(requestSeqNo)
      val movedEvent = awaitReceiveMessage(
        receiveOne(ehConf.receiverTimeout.getOrElse(DefaultReceiverTimeout), "checkCursor move"),
        requestSeqNo)
      val movedSeqNo = movedEvent.iterator.next.getSequenceNumber
      if (movedSeqNo != requestSeqNo) {
        // Track 2: Get partition properties instead of runtime info
        val partitionProps = consumerClient.getPartitionProperties(nAndP.partitionId.toString)

        if (requestSeqNo < partitionProps.getBeginSequenceNumber &&
            movedSeqNo == partitionProps.getBeginSequenceNumber) {
          Future {
            movedEvent
          }
        } else {
          throw new IllegalStateException(
            s"In partition ${nAndP.partitionId}, with consumer group $consumerGroup, " +
              s"request seqNo $requestSeqNo is less than the received seqNo $receivedSeqNo. The earliest seqNo is " +
              s"${partitionProps.getBeginSequenceNumber}, the last seqNo is ${partitionProps.getLastEnqueuedSequenceNumber}, and " +
              s"received seqNo $movedSeqNo")
        }
      } else {
        Future {
          movedEvent
        }
      }
    } else {
      Future {
        event
      }
    }
  }

  private def receive(requestSeqNo: SequenceNumber, batchSize: Int): Iterator[EventData] = {
    val taskId = EventHubsUtils.getTaskId
    val startTimeNs = System.nanoTime()
    def elapsedTimeNs = System.nanoTime() - startTimeNs

    // first check if this call re-executes a stream that has already been received.
    // This situation could happen if multiple actions or writers are using the
    // same stream. In this case, we return the cached data.
    if (cachedData.matchSeqNoAndBatchSize(requestSeqNo, batchSize)) {
      logInfo(s"(TID $taskId) Returned data from cache for namespaceUri: $namespaceUri EventHubNameAndPartition: $nAndP " +
        s"consumer group: $consumerGroup, requestSeqNo: $requestSeqNo, batchSize: $batchSize")
      return cachedData.getCachedDataIterator()
    }

    // Retrieve the events. First, we get the first event in the batch.
    // Then, if the succeeds, we collect the rest of the data.
    val first = Await.result(checkCursor(requestSeqNo), ehConf.internalOperationTimeout)
    // Track 2: Use getSequenceNumber() directly instead of getSystemProperties().getSequenceNumber()
    val firstSeqNo = first.iterator.next.getSequenceNumber
    val batchCount = (requestSeqNo + batchSize - firstSeqNo).toInt

    if (batchCount <= 0) {
      return Iterator.empty
    }

    val theRest = for { i <- 1 until batchCount } yield
      awaitReceiveMessage(receiveOne(ehConf.receiverTimeout.getOrElse(DefaultReceiverTimeout),
                                     s"receive; $nAndP; seqNo: ${requestSeqNo + i}"),
                          requestSeqNo)
    // Combine and sort the data.
    val combined = first ++ theRest.flatten
    // Track 2: Update to use getSequenceNumber() directly
    val sortedSeq = combined.toSeq
      .sortWith((e1, e2) =>
        e1.getSequenceNumber < e2.getSequenceNumber)

    cachedData = new CachedReceivedData(requestSeqNo, batchSize, sortedSeq)

    val sorted = sortedSeq.iterator
    val (result, validate) = sorted.duplicate
    val elapsedTimeMs = TimeUnit.NANOSECONDS.toMillis(elapsedTimeNs)

    // if slowPartitionAdjustment is on, send the partition performance for this batch to the driver
    if (ehConf.slowPartitionAdjustment) {
      sendPartitionPerformanceToDriver(
        PartitionPerformanceMetric(nAndP,
                                   EventHubsUtils.getTaskContextSlim,
                                   requestSeqNo,
                                   batchCount,
                                   elapsedTimeMs))
    }

    if (metricPlugin.isDefined) {
      val (validateSize, batchSizeInBytes) =
        validate
          .map(eventData => (1, eventData.getBody.length.toLong))
          .reduceOption { (countAndSize1, countAndSize2) =>
            (countAndSize1._1 + countAndSize2._1, countAndSize1._2 + countAndSize2._2)
          }
          .getOrElse((0, 0L))
      metricPlugin.foreach(
        _.onReceiveMetric(EventHubsUtils.getTaskContextSlim,
                          nAndP,
                          batchCount,
                          batchSizeInBytes,
                          elapsedTimeMs))
      assert(validateSize == batchCount)
    } else {
      assert(validate.size == batchCount)
    }
    logInfo(s"(TID $taskId) Finished receiving for namespaceUri: $namespaceUri EventHubNameAndPartition: $nAndP " +
      s"consumer group: $consumerGroup, batchSize: $batchSize, elapsed time: $elapsedTimeMs ms")
    result
  }

  private def awaitReceiveMessage[T](awaitable: Awaitable[T], requestSeqNo: SequenceNumber): T = {
    val taskId = EventHubsUtils.getTaskId

    try {
      Await.result(awaitable, ehConf.internalOperationTimeout)
    } catch {
      case e: AwaitTimeoutException =>
        logError(
          s"(TID $taskId) awaitReceiveMessage call failed with timeout. NamespaceUri: $namespaceUri " +
            s"EventHubNameAndPartition: $nAndP consumer group: $consumerGroup. requestSeqNo: $requestSeqNo")

        recreateReceiver(requestSeqNo)
        throw e
    }
  }

  // send the partition perforamcne metric (elapsed time for receiving events in the batch) to the
  // driver without waiting for any response.
  private def sendPartitionPerformanceToDriver(partitionPerformance: PartitionPerformanceMetric) = {
    logDebug(
      s"(Task: ${EventHubsUtils.getTaskContextSlim}) sends PartitionPerformanceMetric: " +
        s"${partitionPerformance} to the driver.")
    try {
      CachedEventHubsReceiver.partitionPerformanceReceiverRef.send(partitionPerformance)
    } catch {
      case e: Exception =>
        logError(
          s"(Task: ${EventHubsUtils.getTaskContextSlim}) failed to send the RPC message containing " +
            s"PartitionPerformanceMetric: ${partitionPerformance} to the driver with error: ${e}.")
    }
  }
}

/**
 * A companion object to the [[CachedEventHubsReceiver]]. This companion object
 * serves as a singleton which carries all the cached receivers on a given
 * Spark executor.
 */
private[spark] object CachedEventHubsReceiver extends CachedReceiver with Logging {

  private val startRecieverTimeNs = System.nanoTime()

  type MutableMap[A, B] = scala.collection.mutable.HashMap[A, B]

  private[this] val receivers = new MutableMap[String, CachedEventHubsReceiver]()

  // RPC endpoint for partition performance communication in the executor
  val partitionPerformanceReceiverRef =
    RpcUtils.makeDriverRef(PartitionPerformanceReceiver.ENDPOINT_NAME,
                           SparkEnv.get.conf,
                           SparkEnv.get.rpcEnv)

  private def key(ehConf: EventHubsConf, nAndP: NameAndPartition): String = {
    (ehConf.connectionString + ehConf.consumerGroup + nAndP.partitionId).toLowerCase
  }

  private[eventhubs] override def receive(ehConf: EventHubsConf,
                                          nAndP: NameAndPartition,
                                          requestSeqNo: SequenceNumber,
                                          batchSize: Int): Iterator[EventData] = {
    val taskId = EventHubsUtils.getTaskId

    logInfo(s"(TID $taskId) EventHubsCachedReceiver look up. For namespaceUri ${ehConf.namespaceUri} " +
      s"EventHubNameAndPartition $nAndP consumer group ${ehConf.consumerGroup.getOrElse(DefaultConsumerGroup)}. " +
      s"requestSeqNo: $requestSeqNo, batchSize: $batchSize")
    var receiver: CachedEventHubsReceiver = null
    receivers.synchronized {
      receiver = receivers.getOrElseUpdate(key(ehConf, nAndP), {
        CachedEventHubsReceiver(ehConf, nAndP, requestSeqNo)
      })
    }
    try {
      receiver.receive(requestSeqNo, batchSize)
    } catch {
      case completionExecution: CompletionException =>
        val exceptionCause = completionExecution.getCause
        if (exceptionCause != null &&  exceptionCause.isInstanceOf[RejectedExecutionException] && exceptionCause.getMessage.contains("ReactorDispatcher instance is closed")) {
          // reactor dispatcher closed case
          logInfo(s"(TID $taskId) EventHubsCachedReceiver receive execution for namespaceUri ${ehConf.namespaceUri} " +
            s"EventHubNameAndPartition $nAndP consumer group ${ehConf.consumerGroup.getOrElse(DefaultConsumerGroup)} " +
            s"failed with $completionExecution. Try to recreate the entire CachedEventHubsReceiver instance in order to " +
            s"use a fresh EventHubClient from the underlying java SDK, then try receiving events again.")
          receiver.client.close();
          receiver = CachedEventHubsReceiver(ehConf, nAndP, requestSeqNo)
          receivers.synchronized {
            receivers.update(key(ehConf, nAndP), receiver)
          }
          receiver.receive(requestSeqNo, batchSize)
        } else if (exceptionCause != null &&  exceptionCause.isInstanceOf[ReceiverDisconnectedException]) {
          logInfo(s"(TID $taskId) EventHubsCachedReceiver receive execution for namespaceUri ${ehConf.namespaceUri} " +
            s"EventHubNameAndPartition $nAndP consumer group ${ehConf.consumerGroup.getOrElse(DefaultConsumerGroup)} " +
            s"failed because another receiver for the same <NS-EH-CG-Part> combo has been created and caused this one " +
            s"to get disconnected. The full error is: $completionExecution. Throw the exception so that the driver can " +
            s"retry the task.")
          throw completionExecution
        } else {
          throw completionExecution
        }

    }
  }

  def apply(ehConf: EventHubsConf,
            nAndP: NameAndPartition,
            startSeqNo: SequenceNumber): CachedEventHubsReceiver = {
    new CachedEventHubsReceiver(ehConf, nAndP, startSeqNo)
  }
}
